[0m16:59:44.525319 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000187D23F4590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000187D00FD1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000187CFFEB750>]}


============================== 16:59:44.540250 | 110f6129-00fb-4600-a14a-ffe09afac847 ==============================
[0m16:59:44.540250 [info ] [MainThread]: Running with dbt=1.9.2
[0m16:59:44.542037 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\aryan\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m16:59:44.543780 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\aryan\OneDrive\Documentos\GitHub\gps_brt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:59:44.546597 [debug] [MainThread]: Command `dbt run` failed at 16:59:44.546374 after 0.23 seconds
[0m16:59:44.547144 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000187D304A520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000187D2F61C70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000187D2F368B0>]}
[0m16:59:44.547688 [debug] [MainThread]: Flushing usage events
[0m16:59:45.882767 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:04:42.089609 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015A2B544590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015A2926D1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015A2914B750>]}


============================== 17:04:42.098515 | ba6dc431-619a-421c-9df6-8cf058db741f ==============================
[0m17:04:42.098515 [info ] [MainThread]: Running with dbt=1.9.2
[0m17:04:42.100271 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\aryan\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:04:42.101106 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\aryan\OneDrive\Documentos\GitHub\gps_brt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:04:42.103827 [debug] [MainThread]: Command `dbt run` failed at 17:04:42.103614 after 0.23 seconds
[0m17:04:42.104350 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015A2C19A520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015A2C0B5C70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015A2C0868B0>]}
[0m17:04:42.104971 [debug] [MainThread]: Flushing usage events
[0m17:04:43.327628 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:05:35.103765 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8F8314590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8F602D1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8F5F0B750>]}


============================== 17:05:35.113210 | 7a393e8d-be76-46dc-b24a-74c4d3c78a4c ==============================
[0m17:05:35.113210 [info ] [MainThread]: Running with dbt=1.9.2
[0m17:05:35.114831 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\aryan\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'C:\\Users\\aryan\\OneDrive\\Documentos\\GitHub\\gps_brt\\logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m17:05:35.118046 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'brt_db'
[0m17:05:35.121100 [debug] [MainThread]: Command `dbt run` failed at 17:05:35.120860 after 0.23 seconds
[0m17:05:35.122347 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8F8F6A650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8F8E81EB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8F8E569C0>]}
[0m17:05:35.123485 [debug] [MainThread]: Flushing usage events
[0m17:05:36.268551 [debug] [MainThread]: An error was encountered while trying to flush usage events
